### PR TITLE
Use locale number separators in wallets & explorer

### LINKED ISSUE #128: Separate groups of thousands in amount display based on region
A user reported:

> those of us in the US do not use ' as the 1000 separator, we use a comma as in 10,000 and not 10'000 can we make this an option as it's totally unnatural to see it like 10'000 in the US thanks much

### PR DESCRIPTION
**Pull request by nop33**
Closes #128

### CODE REVIEW

**Comment by nop33** [comment]
Another complaint regarding this, this time on Reddit: https://www.reddit.com/r/Alephium/comments/1bezpf5/alephium_explorer_formatting_improvement/

cc @mvaivre

**Comment by mvaivre** [comment]
I've been testing it and IMO the new format can be more confusing than before:

**NEW**
image

instead of 
OLD
image

**Comment by nop33** [comment]
> Today, simply switch from using apostrophes to comas for thousand separators.

Is this more common, globally? 

Let's keep these docs in mind when we implement the proper solution: 
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

**Comment by mvaivre** [comment]
Here's what ChatGPT has to say. Switching to coma makes sense IMO.

- In many English-speaking countries and most of Europe, the comma is used as the thousand separator, and the period is used as the decimal separator (e.g., 1,000.00).
- In some European countries and other parts of the world, the roles are reversed: the period is used as the thousand separator, and the comma is used as the decimal separator (e.g., 1.000,00).
- The apostrophe as a thousand separator is less common but is used in some countries, such as Switzerland for Italian-speaking regions (e.g., 1'000.00).

**Comment by nop33** [comment]
Closing PR since we'll never merge this.

**Pull request closed without merging**
