### PR TITLE
Use new explorer backend token metadata endpoints

### PR DESCRIPTION
**Pull request by nop33**
This PR is work in progress. It integrates the new explorer token metadata endpoints in the desktop wallet for testing.

## TODO

- [x] Use new version of @alephium/web3 once the token metadata endpoints are included: https://github.com/alephium/alephium-web3/pull/286
- [x]  Use new endpoints in desktop wallet
- [x] Use new endpoints in mobile wallet
- [x] Use new endpoints in explorer: It is taken care by this PR: https://github.com/alephium/alephium-frontend/pull/174

### CODE REVIEW

**Review by mvaivre — APPROVED** [review]
LGTM!

**Comment by nop33** [comment]
For some weird reason, the Windows build doesn't use the latest web3 version (`0.26.0`) and it fails:

```
src/storage/assets/assetsActions.ts(75,32): error TS2339: Property 'postTokens' does not exist
```
https://github.com/alephium/alephium-frontend/actions/runs/7182428803/job/19558932006?pr=132

Since bun doesn't exist on Windows yet (only Ubuntu and macOS), the way around it we implemented was to:
1. Generate a `yarn.lock` file with a job that runs on Ubuntu so that it can run:
   ```
   bun install --yarn
   ```
2. Upload the generated `yarn.lock` file so that it can then be downloaded by the job that runs on Windows
3. Download it in the Windows job
4. Install npm packages with `yarn install`

Everything seems to have worked in the `generate-lockfile` job: https://github.com/alephium/alephium-frontend/actions/runs/7182428803/job/19558917086?pr=132

I can see `+ @alephium/web3@0.26.0` in the logs of the "Install NPM dependencies" step.

Maybe another bug of bun when generating the lockfile?

**Comment by nop33** [comment]
After inspecting the yarn.lock file I realized that the issue was that we had different versions of the same web3 packages installed across our apps and yarn didn't like this. I changed all of them to the latest.

But not it fails with a different weird error 😞 

```
error Error: https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.13.tgz: Request failed "522 undefined"
```

**Comment by nop33** [comment]
OK, simply rerunning the job worked...

**Review by mvaivre — APPROVED** [review]

**Pull request merged**
