### PR TITLE
Better TX info page

### PR DESCRIPTION
**Pull request by mvaivre**

### CODE REVIEW

**Comment by nop33** [comment]
Also, what about having the amounts stacked below the address instead in the same row? Did you try out to see how it looks? I feel like it would make an easier to understand UI and you'd have less responsiveness issues

**Comment by nop33** [comment]
I quite like it like this 
image

**Comment by mvaivre** [comment]
Thanks for your feedback! I liked to be able to vertically parse the address list and amount list easily. See what I mean? It make it way easier to find what you are looking for when data of the same kind is properly aligned.

**Review by nop33 — COMMENTED** [review]
Hm, ok, you know best!

btw, I still see responsiveness issues:

image

**Comment by mvaivre** [comment]
@nop33 Are you sure you've pulled the last changes before testing? I can't reproduce.

**Pull request merged**
