### PR TITLE
Simplify desktop wallet build and release

### PR DESCRIPTION
**Pull request by nop33**
For a while I want to get rid of the unmaintained `action-electron-builder` action which we had to fork to make it work. In this PR [this whole JS file](https://github.com/nop33/action-electron-builder/blob/master/index.js) is replaced by simple GitHub Action steps.

### CODE REVIEW

**Comment by nop33** [comment]
@mvaivre I added a commit to address a UX issue with UTXO consolidation.

| before | after |
| ------ | ------ |
| image | image |

**Comment by mvaivre** [comment]
This looks good, easy to understand. I guess we have to try it to see if this work?

**Comment by nop33** [comment]
> I guess we have to try it to see if this work?

Mac works, the released files are signed. Linux release also works. Windows fails for the known issue of revoked certificate, this PR has nothing to do with it.

**Comment by nop33** [comment]
@mvaivre Waiting for review :)

**Review by mvaivre — APPROVED** [review]
LGTM!

**Pull request merged**
