### PR TITLE
Display fiat worth of each token in mobile wallet and sort assets of both wallets based on worth

### LINKED ISSUE #403: Order tokens based on their fiat worth in mobile wallet

### LINKED ISSUE #404: Order tokens based on their fiat worth in desktop wallet

### PR DESCRIPTION
**Pull request by nop33**
Related to #244
Closes #403
Closes #404

### CODE REVIEW

**Comment by mvaivre** [comment]
Tested on mobile and desktop, works well! I'm wondering if we should maybe order tokens by fiat worth when it's known.
It seems to be the standard in many wallet. WDYT @VDAODAO?

**Comment by nop33** [comment]
> I'm wondering if we should maybe order tokens by fiat worth when it's known.

I am not sure what you mean. This is what was implemented, with exception of ALPH that is always shown first.

**Comment by VDAODAO** [comment]
I've checked in a few different wallets I have and it always works like this: ranked by fiat value (trust, metamask, keplr, cobo, live, phantom). Those who don't have a fiat value can then be ranked below by either name or numerical value of units.

**Comment by mvaivre** [comment]
> I am not sure what you mean. This is what was implemented, with exception of ALPH that is always shown first.

**Comment by VDAODAO** [comment]
@mvaivre i agree with that 100%

**Comment by nop33** [comment]
@mvaivre @VDAODAO done, pushed

**Review by mvaivre — APPROVED** [review]

**Pull request merged**
