### PR TITLE
Integrate mobile wallet to Crowdin

### PR DESCRIPTION
**Pull request by nop33**
This PR:
1. Sets up `react-i18n` in mobile wallet
2. Creates `translation.json` English source file with the complete list of all translatable strings
3. Integrates it to Crowdin

It also:
1. Deletes unused files after using `npx unimported` (useful tool)

### CODE REVIEW

**Comment by mvaivre** [comment]
Awesome! Code looks good! Were you able to automatize some of the string wrapping with t(), or did you go through all the strings manually? :P 

I started testing and I see an error on iOS: 
image

**Comment by mvaivre** [comment]
I've added French translations in [this PR](https://github.com/alephium/alephium-frontend/pull/672). Should we add a language settings to test it out?

**Comment by nop33** [comment]
> did you go through all the strings manually? :P

this.

**Comment by nop33** [comment]
> I started testing and I see an error on iOS:

I see it too, but it doesn't affect anything.

**Comment by nop33** [comment]
> I've added French translations in https://github.com/alephium/alephium-frontend/pull/672. Should we add a language settings to test it out?

Sure! But let's merge this one first so that the strings go to Crowdin and the translators can start translating. WDYT?

**Review by mvaivre — APPROVED** [review]
🚀

**Pull request merged**
